server:
    port: 18003
spring:
    application:
        name: name-admin
    cloud:
        sentinel:
            enabled: true # 是否开启。默认为 true 开启
            eager: true # 是否饥饿加载。默认为 false 关闭
            transport:
                dashboard: 127.0.0.1:8080
                port: 8719
                clientIp: 127.0.0.1
            filter:
                url-patterns: /**
            web-context-unify: false #默认将调用链路收敛

    profiles:
        active: dev
#
#management:
#    endpoint:
#        sentinel:
#            enabled: true
#
#    health:
#        sentinel:
#            enabled: true
feign:
    sentinel:
        enabled: true
